import { style } from "@vanilla-extract/css"
export const worksStyle = {
  wrap: style({
    position: "relative",
    width: "100%",
    height: "100%",
    overflow: "hidden",
  }),
  h1: style({
    width: "fit-content",
    height: "fit-content",
    minHeight: "0vw",
    position: "absolute",
    fontSize: "clamp(180px, calc(11.25rem + ((1vw - 7px) * 22.9508)), 460px)",
    fontWeight: "400",
    left: "6%",
    top: "-7%",
  }),
  works: style({
    width: "100%",
    display: "flex",
    flexDirection: "column",
    paddingTop: "20%",
  }),
  top: style({
    display: "flex",
    border: "1px rgb(0,0,0,0.3) solid",
    boxSizing: "border-box",
  }),
  topSquare: style({
    width: "36%",
    height: "100%",
    display: "flex",
    borderRight: "1px rgb(0,0,0,0.3) solid",
    boxSizing: "border-box",
  }),
  innerRow: style({
    width: "94%",
    height: "94%",
    display: "flex",
    alignSelf: "center",
    overflow: "hidden",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    margin: "0 auto",
  }),
  innerColumn: style({
    width: "94%",
    height: "94%",
    display: "flex",
    flexDirection: "column",
    alignSelf: "center",
    overflow: "hidden",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    margin: "0 auto",
  }),
  topRight: style({
    width: "64%",
    height: "100%",
    display: "flex",
  }),
  bottom: style({
    display: "flex",
    border: "1px rgb(0,0,0,0.3) solid",
    borderTop: "none",
    boxSizing: "border-box",
  }),
  bottomLeft: style({
    width: "30%",
    display: "flex",
    borderRight: "1px rgb(0,0,0,0.3) solid",
    boxSizing: "border-box",
  }),
  bottomRight: style({
    width: "70%",
    display: "flex",
    flexWrap: "wrap",
  }),
  bottomRight1: style({
    width: "50%",
    display: "flex",
    borderRight: "1px rgb(0,0,0,0.3) solid",
    boxSizing: "border-box",
  }),
  bottomRight2: style({
    width: "50%",
    display: "flex",
  }),
  bottomRight3: style({
    width: "100%",
    display: "flex",
    borderTop: "1px rgb(0,0,0,0.3) solid",
    boxSizing: "border-box",
  }),
}
